name: tallermecanico
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.2 
  cloud_firestore: ^5.6.11
  firebase_core: ^3.15.1

  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/imgTaller.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/imgTaller.png
    - assets/images/logoTaller.png
    - assets/images/imgTaller1.png
    - assets/images/fondoTaller.png
    - assets/images/clienteLogo.png