name: tallermecanico
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.0 
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0

  provider: ^6.1.1


  # Para cámara y fotos
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  
  # Para Google Drive
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  
  # Para manejo de archivos
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/imgTaller.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/imgTaller.png
    - assets/images/logoTaller.png
    - assets/images/imgTaller1.png
    - assets/images/fondoTaller.png
    - assets/images/clienteLogo.png
    - assets/images/clienteLogo1.png
    - assets/images/clienteLogo2.png