// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkqq8ljvdEoXPrCmdYyhb_ElPI3-nqB_c',
    appId: '1:950160650466:web:f72573d01b28779e2c2ebb',
    messagingSenderId: '950160650466',
    projectId: 'tallermec-4e33e',
    authDomain: 'tallermec-4e33e.firebaseapp.com',
    storageBucket: 'tallermec-4e33e.firebasestorage.app',
    measurementId: 'G-4EN864CW33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Vy4Sy1pwpiOdNhbiv21K8zor4k4FWCk',
    appId: '1:950160650466:android:f64cbaff105715ab2c2ebb',
    messagingSenderId: '950160650466',
    projectId: 'tallermec-4e33e',
    storageBucket: 'tallermec-4e33e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt-hlefyElgt5dFn34X3mLIgSM5q07koM',
    appId: '1:950160650466:ios:eea0a623f5e512872c2ebb',
    messagingSenderId: '950160650466',
    projectId: 'tallermec-4e33e',
    storageBucket: 'tallermec-4e33e.firebasestorage.app',
    iosBundleId: 'com.taller.tallermecanico',
  );
}
